### ISSUE TITLE
add option for 45 degrees (or, optimally, other angles)

### ISSUE THREAD

**Issue by hellochar** [palantir/svg-typewriter#50]
Probably also fixes #25

**Comment by themadcreator** [comment]
Options for bounding box and line wrapping:

![image](https://cloud.githubusercontent.com/assets/569364/22752347/0a83509a-eded-11e6-9c13-39915dadf66c.png)

**Comment by themadcreator** [comment]
Or maybe:
![image](https://cloud.githubusercontent.com/assets/569364/22752707/669296b0-edee-11e6-8f94-8d51a024ac62.png)

**Comment by themadcreator** [comment]
Also, how will x/y alignment work for this? If i say x-align center, what does that mean?
